import turtle 
# my_turtle=turtle.Turtle()
wn = turtle.Screen()
wn.bgcolor('#FFB3B3')
wn.title("ARK")
turtle.color('#2A0944')
turtle.write("Happy Friendship Day",align="center",font=("Arial",24,"normal","italic"))
# turtle.fillcolor("orange")
turtle.down()
turtle.done()
